# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-13 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('games', multiselectfield.db.fields.MultiSelectField(choices=[('ArbolMusical', 'ArbolMusical'), ('Rio', 'Rio'), ('ArenaMagica', 'ArenaMagica'), ('DondeQuedoLaBolita', 'DondeQuedoLaBolita'), ('Tesoro', 'Tesoro'), ('JuegoDeSombras', 'JuegoDeSombras'), ('PruebaEcologica', 'PruebaEcologica')], max_length=85)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Sesiones de juego',
                'ordering': ('order',),
                'verbose_name_plural': 'Sesiones de juego',
            },
        ),
        migrations.RemoveField(
            model_name='childrentowiisland',
            name='arbolmusicaltutorial',
        ),
        migrations.RemoveField(
            model_name='childrentowiisland',
            name='riotutorial',
        ),
        migrations.RemoveField(
            model_name='childrentowiisland',
            name='tesorotutorial',
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='arbol_first_time',
            field=models.BooleanField(db_column='arbolMusicalTutorial', default=False),
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='arena_first_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='bolita_first_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='rio_first_time',
            field=models.BooleanField(db_column='rioTutorial', default=False),
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='sombras_first_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='tesoro_first_time',
            field=models.BooleanField(db_column='tesoroTutorial', default=False),
        ),
    ]
