# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-18 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('levels', '0003_auto_20180913_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='children',
            field=models.ManyToManyField(related_name='sessions', to='accounts.Children'),
        ),
    ]
