# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0006_auto_20180920_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrentowiisland',
            name='arbol_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
