# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0007_childrentowiisland_arbol_first_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='unpacks1correct',
            new_name='arrange1_correct',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unpacks1incorrect',
            new_name='arrange1_incorrect',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unpacks1repeated',
            new_name='arrange1_perseveration',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unpacks2correct',
            new_name='arrange2_correct',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unpacks2incorrect',
            new_name='arrange2_incorrect',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unpacks2repeated',
            new_name='arrange2_perseveration',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unpacks3correct',
            new_name='arrange3_correct',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unpacks3incorrect',
            new_name='arrange3_incorrect',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unpacks3repeated',
            new_name='arrange3_perseveration',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unpackfourfirstsample',
            new_name='arrange_primacy',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unpackfourlastsample',
            new_name='arrange_recence',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unpackspacialprecisionsample',
            new_name='arrange_spacialprecision_sample',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unpacktimeofcomp',
            new_name='arrange_time',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='playeraddress',
            new_name='boarding_address',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='playerage',
            new_name='boarding_age',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='playerbirthday',
            new_name='boarding_birthday',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='playercurrentdate',
            new_name='boarding_currentdate',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='playername',
            new_name='boarding_name',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='inputagetimeofcomp',
            new_name='boarding_time1',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='buytickettimeofcomp',
            new_name='boarding_time2',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='coinsclicksbeforemin',
            new_name='coins_clickfinish_before_min',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='coinsextracorrect',
            new_name='coins_extra_correct',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='coinsextraincorrect',
            new_name='coins_extra_incorrect',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='coinsextramissed',
            new_name='coins_extra_missed',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='coinsmincorrect',
            new_name='coins_min_correct',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='coinsminincorrect',
            new_name='coins_min_incorrect',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='coinsselected',
            new_name='coins_selected',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='coinstimeofcomp',
            new_name='coins_time',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='flyplanecorrect',
            new_name='flyplane_correct',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='flyplanegreencorrect',
            new_name='flyplane_greencorrect',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='flyplanegreenincorrect',
            new_name='flyplane_greenincorrect',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='flyplanegreenmissed',
            new_name='flyplane_greenmissed',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='flyplaneincorrect',
            new_name='flyplane_incorrect',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='flyplanemissed',
            new_name='flyplane_missed',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='flyplanetimeofcomp',
            new_name='flyplane_time',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab1crosses',
            new_name='lab1_crosses',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab1deadends',
            new_name='lab1_deadends',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab1hits',
            new_name='lab1_hits',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab1latency',
            new_name='lab1_latency',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab1time',
            new_name='lab1_time',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab2crosses',
            new_name='lab2_crosses',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab2deadends',
            new_name='lab2_deadends',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab2hits',
            new_name='lab2_hits',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab2latency',
            new_name='lab2_latency',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab2time',
            new_name='lab2_time',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab3crosses',
            new_name='lab3_crosses',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab3deadends',
            new_name='lab3_deadends',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab3hits',
            new_name='lab3_hits',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab3latency',
            new_name='lab3_latency',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='lab3time',
            new_name='lab3_time',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='labtimeofcomp',
            new_name='lab_time',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='packreversescore',
            new_name='packbackward_score',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='packnormalscore',
            new_name='packforward_score',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unpackfirstcorrect',
            new_name='unpack_correct',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='waitroomcorrect',
            new_name='waitroom_correct',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='waitroomincorrect',
            new_name='waitroom_incorrect',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='weathercongruence',
            new_name='weather_coherence',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='weatherobjectpacked',
            new_name='weather_object_packed',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='labxcrosses',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='labxdeadends',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='labxhits',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='unpackperctotalcorrect',
        ),
        migrations.AddField(
            model_name='prueba',
            name='application_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prueba',
            name='arrange_amplitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='arrange_correct_mlatency',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='arrange_incorrect_mlatency',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='arrange_incorrect_repeated',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='prueba',
            name='arrange_learningcurve',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='arrange_perc_correct',
            field=models.DecimalField(blank=True, db_column='unPackPercTotalCorrect', decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='arrange_spacialprecision_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='arrange_storage_efficency1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='arrange_storage_efficency2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='boarding_latency',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='coins_correct_mlatency',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='coins_incorrect_mlatency',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='coins_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='coins_organization_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='coins_tutorial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='device',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prueba',
            name='flyplane_series',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='flyplane_tutorial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='lab1_changeofroutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='lab2_changeofroutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='lab3_changeofroutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='lab_mcrosses',
            field=models.DecimalField(blank=True, db_column='labXCrosses', decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='lab_mdeadends',
            field=models.DecimalField(blank=True, db_column='labXDeadEnds', decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='lab_mhits',
            field=models.DecimalField(blank=True, db_column='labXHits', decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='lab_start_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='packbackward_incorrect_secuence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='packbackward_intrusions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='packbackward_time',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='packbackward_tutorial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='packforward_incorrect_secuence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='packforward_instrusions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='packforward_time',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='packforward_tutorial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='total_time',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='unpack_bad_recognition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='unpack_first_correct',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='prueba',
            name='unpack_first_selected',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='prueba',
            name='unpack_incorrect',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='unpack_perseveration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='unpack_time',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='version',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prueba',
            name='waitroom_correct_mlatency',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='waitroom_incorrect_mlatency',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='waitroom_tutorial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='weather_latency',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
