# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0009_auto_20180928_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='application_number',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='device',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='version',
        ),
        migrations.AddField(
            model_name='header',
            name='application_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='header',
            name='version',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
