# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0010_auto_20180928_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='application_number',
        ),
    ]
