# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0011_remove_header_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='application_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
