# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-04 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0013_auto_20181001_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='flyplane_correct_mlatency',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='flyplane_greencorrect_mlatency',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='flyplane_greenincorrect_mlatency',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='flyplane_incorrect_mlatency',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
