# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-05 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0015_auto_20181004_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenamagica',
            name='sublevel2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='sublevel3',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
