# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0016_auto_20181005_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='coins_pattern_type',
            field=models.IntegerField(blank=True, db_column='coinsPatternType', null=True),
        ),
    ]
