# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0017_prueba_coins_pattern_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrentowiisland',
            name='arbol_level_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='arena_level_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='arena_level_set2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='bolita_level_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='island_shopping_list',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='rio_level_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='sombras_level_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childrentowiisland',
            name='tesoro_level_set',
            field=models.BooleanField(default=False),
        ),
    ]
