# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0018_auto_20181116_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbolmusical',
            name='correct_after_clue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='correct_before_clue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='dad_bird_listened_post',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='dad_bird_listened_pre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='errors_after_clue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='errors_before_clue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='essay_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='final_Difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='final_Level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='initial_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='initial_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='played_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='played_levels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='session_correct_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='session_errors_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='total_clues',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='total_correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbolmusical',
            name='total_errors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='change_level_clousure',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='change_level_motor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='change_level_overlapping',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='current_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='current_level_clousre',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='current_level_motor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='current_level_overlapping',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='initial_level_clousre',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='initial_level_motor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='initial_level_overlapping',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='overdraw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='played_levels',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='session_accuracy_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='session_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='session_overdraw_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='time_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arenamagica',
            name='types_levels',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dondequedolabolita',
            name='correct_monkeys',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dondequedolabolita',
            name='current_difficulty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dondequedolabolita',
            name='current_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dondequedolabolita',
            name='errors_monkeys',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dondequedolabolita',
            name='initial_difficulty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dondequedolabolita',
            name='initial_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dondequedolabolita',
            name='latency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dondequedolabolita',
            name='played_difficulty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dondequedolabolita',
            name='played_levels',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dondequedolabolita',
            name='session_correct_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dondequedolabolita',
            name='session_errors_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dondequedolabolita',
            name='session_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dondequedolabolita',
            name='session_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='game_frequency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='last_session_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='total_sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='total_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='totalcorrect_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='totalerrors_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='current_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='current_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='diffrence_in_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='initial_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='initial_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='played_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='played_levels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='requestreminder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='session_correct_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='session_errors_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='session_maxobjects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='session_minobjects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='session_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recolecciontesoro',
            name='total_second_chances',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rio',
            name='current_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rio',
            name='current_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rio',
            name='initial_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rio',
            name='initial_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rio',
            name='played_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rio',
            name='played_levels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rio',
            name='session_correct_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rio',
            name='session_errors_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rio',
            name='target_correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rio',
            name='target_errors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rio',
            name='target_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sombras',
            name='current_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sombras',
            name='initial_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sombras',
            name='latencies',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sombras',
            name='played_levels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sombras',
            name='session_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sombras',
            name='sessioncorrect_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sombras',
            name='sessionerrors_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arenamagica',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
