# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-06 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0022_arbolmusicalv2_arenamagicav2_dondequedolabolitav2_recolecciontesorov2_riov2_sombrasv2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbolmusicalv2',
            old_name='final_difficulty',
            new_name='current_difficulty',
        ),
        migrations.RenameField(
            model_name='arbolmusicalv2',
            old_name='final_level',
            new_name='current_level',
        ),
    ]
