# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-06 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0023_auto_20190206_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='sombrasv2',
            name='current_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
