# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-07 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0024_sombrasv2_current_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbolmusicalv2',
            name='total_clues',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbolmusicalv2',
            name='total_correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbolmusicalv2',
            name='total_errors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
