# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0026_auto_20190319_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='weather_object_packed',
            field=models.CharField(blank=True, db_column='weatherObjectPacked', max_length=1000, null=True),
        ),
    ]
