# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-03 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0027_auto_20190319_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Average',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=15)),
                ('coins_min_correct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coins_extra_missed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arrange_total_correct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arrange_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unpack_correct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('packforward_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('packbackward_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('waitroom_correct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flyplane_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flyplane_greencorrect', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flyplane_greenincorrect', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flyplane_correct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flyplane_incorrect', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lab_hits_sum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lab_crosses_sum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lab_deadends_sum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lab_time_sum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lab_latency_sum', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Promedio',
            },
        ),
        migrations.CreateModel(
            name='Quartile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=15)),
                ('coins_min_correct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coins_extra_missed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arrange_total_correct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arrange_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unpack_correct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('packforward_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('packbackward_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('waitroom_correct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flyplane_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flyplane_greencorrect', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flyplane_greenincorrect', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flyplane_correct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flyplane_incorrect', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lab_hits_sum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lab_crosses_sum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lab_deadends_sum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lab_time_sum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lab_latency_sum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cuartil',
                'verbose_name_plural': 'Cuartiles',
            },
        ),
    ]
