# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-15 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0029_childrentowiisland_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrentowiisland',
            name='order_missions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
