# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-16 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0030_childrentowiisland_order_missions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='arrange_amplitude',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
