# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-22 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0031_auto_20190516_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='average',
            name='coins_min_correct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='quartile',
            name='coins_min_correct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
