# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-17 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0033_auto_20190522_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='arrange_perc_correct',
            field=models.DecimalField(blank=True, db_column='unPackPercTotalCorrect', decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='lab_mcrosses',
            field=models.DecimalField(blank=True, db_column='labXCrosses', decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='lab_mdeadends',
            field=models.DecimalField(blank=True, db_column='labXDeadEnds', decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='lab_mhits',
            field=models.DecimalField(blank=True, db_column='labXHits', decimal_places=4, max_digits=10, null=True),
        ),
    ]
