# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181010_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='openpay_token',
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
