# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181023_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='link_id',
            field=models.CharField(max_length=15),
        ),
    ]
