# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181025_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedAccountsChildrens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.BooleanField(default=False)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='accounts.Children')),
            ],
            options={
                'verbose_name_plural': 'Option de Cuentas Ligadas',
            },
        ),
        migrations.RemoveField(
            model_name='linkedaccountsoptions',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='linkedaccountsoptions',
            name='linked_account_id',
        ),
        migrations.AlterModelOptions(
            name='linkedaccounts',
            options={'verbose_name_plural': 'Usuarios Vinculados'},
        ),
        migrations.RemoveField(
            model_name='linkedaccounts',
            name='auth_u1',
        ),
        migrations.RemoveField(
            model_name='linkedaccounts',
            name='auth_u2',
        ),
        migrations.AlterField(
            model_name='linkedaccounts',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_linked_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linkedaccounts',
            name='shared_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_linked_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LinkedAccountsOptions',
        ),
        migrations.AddField(
            model_name='linkedaccountschildrens',
            name='linked_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='accounts.LinkedAccounts'),
        ),
    ]
