# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181025_1221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='linkedaccounts',
            unique_together=set([('owner_user', 'shared_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='linkedaccountschildrens',
            unique_together=set([('linked_account', 'cid')]),
        ),
    ]
