# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 03:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181023_2259'),
        ('suscriptions', '0002_verificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscriptionchildren',
            name='children',
        ),
        migrations.RemoveField(
            model_name='suscriptionchildren',
            name='suscription',
        ),
        migrations.RemoveField(
            model_name='suscriptionchildren',
            name='type',
        ),
        migrations.AlterModelOptions(
            name='suscription',
            options={'verbose_name': 'Suscription'},
        ),
        migrations.RemoveField(
            model_name='suscription',
            name='key',
        ),
        migrations.RemoveField(
            model_name='suscription',
            name='max_kids',
        ),
        migrations.AddField(
            model_name='suscription',
            name='children',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suscription', to='accounts.Children'),
        ),
        migrations.AddField(
            model_name='suscription',
            name='finished_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscription',
            name='is_recurrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suscription',
            name='order',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscription',
            name='trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suscription',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suscriptions', to='suscriptions.SuscriptionType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suscriptiontype',
            name='name',
            field=models.CharField(choices=[('unsuscribe', 'Sin subscripción'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('monthly_inApp', 'Mensual comprada desde la App'), ('quarterly_inApp', 'Trimestral comprada desde la App')], default='unsuscribe', max_length=50),
        ),
        migrations.DeleteModel(
            name='SuscriptionChildren',
        ),
    ]
