# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptions', '0003_auto_20181023_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscription',
            name='children',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscription', to='accounts.Children'),
        ),
    ]
