# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptions', '0004_auto_20181025_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='promos',
            old_name='ammount',
            new_name='amount',
        ),
    ]
